generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_group
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at:     { date_format: y/MM/dd HH:mm:ss }
        updated_at:     { date_format: y/MM/dd HH:mm:ss }
      list:
        title:   Groups management
        batch_actions: {}
        max_per_page: 20
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
